name: 'icu'
on:
  workflow_dispatch:
jobs:
  icu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        icu: [50.2, 51.3, 52.2, 53.2, 54.2, 55.2, 56.2, 57.2, 58.3, 59.2, 60.3, 61.2, 62.2, 63.2, 64.2, 65.1, 66.1, 67.1, 68.1, 68.2]
    name: icu4c
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build icu
        env:
          ICU: ${{ matrix.icu }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKSPACE: ${{ github.workspace }}
        run: |
          existing_version=$(gh release view icu4c 2>/dev/null | grep -Po $ICU | head -n 1)
          if [ "$ICU" != "$existing_version" ]; then
            bash src/build-icu4c.sh
            bash src/release-icu4c.sh
          else
            echo "icu4c $ICU build exists"
          fi
