name: 'php-intl'
on:
  push:
jobs:
  php-intl:
    if: "contains(github.event.head_commit.message, 'build-intl')"
    container: ubuntu:bionic
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4']
        icu: [67.1, 66.1, 65.1, 64.2, 63.2, 62.2, 61.2, 60.3, 59.2, 58.3, 57.2, 56.2, 55.2, 54.2, 53.2, 52.2, 51.3, 50.2]
    name: php-intl
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update intl
        env:
          ICU: ${{ matrix.icu }}
          BINTRAY_KEY: ${{ secrets.bintray_key }}
          BINTRAY_REPO: icu4c
          BINTRAY_USER: ${{ github.repository_owner }}
          VERSION: ${{ matrix.php }}
        run: |
          apt-get -y update
          apt-get install -y sudo curl
          existing_version=$(curl --user "$BINTRAY_USER":"$BINTRAY_KEY" -s https://api.bintray.com/packages/"$BINTRAY_USER"/"$BINTRAY_REPO"/php-intl | grep -Po "$VERSION-$ICU" | head -n 1)
          if [ "$VERSION-$ICU" != "$existing_version" ]; then
            sudo apt-get install -y gnupg make automake zstd software-properties-common pkg-config
            LC_ALL=C.UTF-8 sudo DEBIAN_FRONTEND=noninteractive apt-add-repository ppa:ondrej/php -y
            sudo DEBIAN_FRONTEND=noninteractive apt-get install -y php$VERSION php$VERSION-xml php$VERSION-dev
            ext_dir=$(php -i | grep "extension_dir => /" | sed -e "s|.*=> s*||")
            scan_dir=$(php --ini | grep additional | sed -e "s|.*: s*||")
            ini_file=$(php --ini | grep "Loaded Configuration" | sed -e "s|.*:s*||" | sed "s/ //g")
            pecl_file="$scan_dir"/99-pecl.ini
            get_tag() {
              echo "php-$(php -v | head -n 1 | cut -f 2 -d ' ' | cut -f 1 -d '-')"
            }
            get_php() {
              curl -sL "https://github.com/php/php-src/archive/$tag.tar.gz" | tar xzf - -C "/tmp"
            }
            check_extension() {
              extension=$1
              if [ "$extension" != "mysql" ]; then
                php -m | grep -i -q -w "$extension"
              else
                php -m | grep -i -q "$extension"
              fi
            }
            enable_extension() {
              if ! check_extension "$1" && [ -e "$ext_dir/$1.so" ]; then
                echo "$2=$1.so" >>"$pecl_file"
              fi
            }
            install_icu() {
              sudo curl -o /tmp/icu.tar.zst -sL https://dl.bintray.com/shivammathur/icu4c/icu4c-$ICU.tar.zst
              sudo tar -I zstd -xf /tmp/icu.tar.zst -C /usr/local
              sudo cp -r /usr/local/icu/* /usr/
              sudo cp -r /usr/local/icu/lib/* /usr/lib/x86_64-linux-gnu/
            }
            install_intl() {
              tag=$(get_tag)
              get_php
              (
                cd "/tmp/php-src-$tag/ext/intl" || exit 1
                phpize && sudo ./configure --with-php-config="$(command -v php-config)" --enable-intl
                sudo make CXXFLAGS="-O2 -std=c++11 -DU_USING_ICU_NAMESPACE=1 $CXXFLAGS"
                sudo cp ./modules/* "$ext_dir/"
                enable_extension intl extension
              )
            }
            install_icu
            install_intl
            icu_version=$(php -i | grep "ICU version =>" | sed -e "s|.*=> s*||")
            [ "$icu_version" != "$ICU" ] && exit 1
            cd "$ext_dir" || exit 1
            curl --user "$BINTRAY_USER":"$BINTRAY_KEY" -X DELETE https://api.bintray.com/content/"$BINTRAY_USER"/"$BINTRAY_REPO"/php"$VERSION"-intl-"$ICU".so || true
            curl --user "$BINTRAY_USER":"$BINTRAY_KEY" -T intl.so https://api.bintray.com/content/"$BINTRAY_USER"/"$BINTRAY_REPO"/php-intl/"$VERSION-$ICU"/php"$VERSION"-intl-"$ICU".so || true
            curl --user "$BINTRAY_USER":"$BINTRAY_KEY" -X POST https://api.bintray.com/content/"$BINTRAY_USER"/"$BINTRAY_REPO"/php-intl/"$VERSION-$ICU"/publish || true
          else
            echo "intl $VERSION-$ICU build exists"
          fi          